### ISSUE TITLE
CSS affecting pages?

### ISSUE THREAD

**Issue by jscher2000** [kinitawowi/linkvisitor-firefox#3]
I pleased this extension is being ported to WebExtensions, and of course, growing pains are expected.

This rule from moz-extension://{randomized}/content/styles.css somehow is overriding normal page styles causing layout issues (e.g., ugly page edges, horizontal scroll bar) on one of my pages:

```
body {
  padding: 0;
  margin: 0; }
```

Affected page: https://www.jeffersonscher.com/gm/url-bar-tweaks.html

Is that essential and/or is there some way to limit its effect?

**Comment by kinitawowi** [comment]
That shouldn't really have been exposed as it only required for the internal pages,   I've updated the styles so this will no longer affect any pages.

**Comment by jscher2000** [comment]
Thank you for the speedy fix!
